---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13
  always_update_cookbooks: <%= !ENV['CI'] %>

verifier:
  name: inspec
  attributes:
    dnsimple_token: <%= ENV['DNSIMPLE_ACCESS_TOKEN'] %>
    test_domain: dnsimple.xyz

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6
  - name: centos-7
  - name: freebsd-11

suites:
  - name: create_record
    run_list:
      - recipe[dnsimple_test::reset_test_environment]
      - recipe[dnsimple_test::create_record]
    attributes:
      dnsimple:
        access_token: <%= ENV['DNSIMPLE_ACCESS_TOKEN'] %>
        base_url: https://api.sandbox.dnsimple.com
        test_domain: dnsimple.xyz
  - name: update_record
    run_list:
      - recipe[dnsimple_test::reset_test_environment]
      - recipe[dnsimple_test::update_record]
    attributes:
      dnsimple:
        access_token: <%= ENV['DNSIMPLE_ACCESS_TOKEN'] %>
        base_url: https://api.sandbox.dnsimple.com
        test_domain: dnsimple.xyz
  - name: install_certificate
    run_list:
      - recipe[dnsimple_test::reset_test_environment]
      - recipe[dnsimple_test::install_certificate]
    attributes:
      dnsimple:
        access_token: <%= ENV['DNSIMPLE_ACCESS_TOKEN'] %>
        base_url: https://api.sandbox.dnsimple.com
        test_domain: dnsimple.xyz
