---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: <%= !ENV['CI'] %>

verifier:
  name: inspec
  inspec_tests:
    - test/smoke/default

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.7

suites:
  - name: chef12
    provisioner:
      require_chef_omnibus: 12
    run_list:
      - recipe[dnsimple_test::default]
    attributes:
