---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12
  always_update_cookbooks: <%= !ENV['CI'] %>

verifier:
  name: inspec
  attributes:
    dnsimple_token: <%= ENV['DNSIMPLE_ACCESS_TOKEN'] %>
    test_domain: dnsimple.net

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.7

suites:
  - name: create_record
    run_list:
      - recipe[dnsimple_test::reset_test_environment]
      - recipe[dnsimple_test::create_record]
    attributes:
      dnsimple:
        access_token: <%= ENV['DNSIMPLE_ACCESS_TOKEN'] %>
        base_url: https://api.sandbox.dnsimple.com
        test_domain: dnsimple.net
