language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
before_script:
  - bundle exec berks install
script:
  - bundle exec rspec spec
  - bundle exec rubocop
  - bundle exec foodcritic .
