sudo: required

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

services: docker

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
    - secure: IfD/3A3IPxozFCSTlI5q6PIr1D78WupjhZVU5RlvDRsuajZuhCJHYHQvD1SI0cLAE+MG3XPhg8BXbPDtHGPCpNKybEFhWlRU9tghTxpzijMBvImBVPNzo8otn8ywvpw1XSFHKd79dFj1SRZqWbEFW4G/JFHarxl9svggyrfMTx8=
  matrix:
    # Split up the test-kitchen run to avoid exceeding 50 minutes:
    - TASK="quick"
    - TASK="integration:dokken" ACTION="verify" INSTANCE=create-record-centos-6 DNSIMPLE_TEST_DOMAIN=create-centos-6-dnsimple.xyz
    - TASK="integration:dokken" ACTION="verify" INSTANCE=create-record-centos-7 DNSIMPLE_TEST_DOMAIN=create-centos-7-dnsimple.xyz
    - TASK="integration:dokken" ACTION="verify" INSTANCE=create-record-ubuntu-1404 DNSIMPLE_TEST_DOMAIN=create-ubuntu-14-dnsimple.xyz
    - TASK="integration:dokken" ACTION="verify" INSTANCE=create-record-ubuntu-1604 DNSIMPLE_TEST_DOMAIN=create-ubuntu-16-dnsimple.xyz
    - TASK="integration:dokken" ACTION="verify" INSTANCE=create-record-ubuntu-1804 DNSIMPLE_TEST_DOMAIN=create-ubuntu-18-dnsimple.xyz
    - TASK="integration:dokken" ACTION="verify" INSTANCE=update-record-centos-6 DNSIMPLE_TEST_DOMAIN=update-centos-6-dnsimple.xyz
    - TASK="integration:dokken" ACTION="verify" INSTANCE=update-record-centos-7 DNSIMPLE_TEST_DOMAIN=update-centos-7-dnsimple.xyz
    - TASK="integration:dokken" ACTION="verify" INSTANCE=update-record-ubuntu-1404 DNSIMPLE_TEST_DOMAIN=update-ubuntu-14-dnsimple.xyz
    - TASK="integration:dokken" ACTION="verify" INSTANCE=update-record-ubuntu-1604 DNSIMPLE_TEST_DOMAIN=update-ubuntu-16-dnsimple.xyz
    - TASK="integration:dokken" ACTION="verify" INSTANCE=update-record-ubuntu-1804 DNSIMPLE_TEST_DOMAIN=update-ubuntu-18-dnsimple.xyz

matrix:
  fast_finish: true

install: echo "skip bundle install"

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef gem install dnsimple

script: chef exec rake "$TASK[$INSTANCE, $CONCURRENCY, $ACTION]"

notifications:
  email: false
  slack:
    secure: S/tClOuaGnhxdCkyc3WT0kWy9fP4a9dI7Ha0Pk0sjC0Fy1+0V/AShxwfgzJdGlzvbsRlCXmkE8W4BEQmZ0HjiPZgrvOx9mxv1krbBaO+eZDiSJIv2NgkgbwcxfraD+V3s4Mo8q3/FtS27diBOOUip4xqETsAIx0X86ZjHcb21ew=
