dist: focal

services: docker

env:
  global:
    - CHEF_LICENSE="accept-silent"
    - secure: IfD/3A3IPxozFCSTlI5q6PIr1D78WupjhZVU5RlvDRsuajZuhCJHYHQvD1SI0cLAE+MG3XPhg8BXbPDtHGPCpNKybEFhWlRU9tghTxpzijMBvImBVPNzo8otn8ywvpw1XSFHKd79dFj1SRZqWbEFW4G/JFHarxl9svggyrfMTx8=
  matrix:
    # Split up the test-kitchen run to isolate failures in a large suite
    - TASK="quick"
    - TASK="kitchen" KITCHEN_REGEXP=create-record-centos-6 DNSIMPLE_TEST_DOMAIN=create-centos-6-dnsimple.xyz
    - TASK="kitchen" KITCHEN_REGEXP=create-record-centos-7 DNSIMPLE_TEST_DOMAIN=create-centos-7-dnsimple.xyz
    - TASK="kitchen" KITCHEN_REGEXP=create-record-ubuntu-1804 DNSIMPLE_TEST_DOMAIN=create-ubuntu-18-dnsimple.xyz
    - TASK="kitchen" KITCHEN_REGEXP=create-record-ubuntu-2004 DNSIMPLE_TEST_DOMAIN=create-ubuntu-20-dnsimple.xyz
    - TASK="kitchen" KITCHEN_REGEXP=update-record-centos-6 DNSIMPLE_TEST_DOMAIN=update-centos-6-dnsimple.xyz
    - TASK="kitchen" KITCHEN_REGEXP=update-record-centos-7 DNSIMPLE_TEST_DOMAIN=update-centos-7-dnsimple.xyz
    - TASK="kitchen" KITCHEN_REGEXP=update-record-ubuntu-1804 DNSIMPLE_TEST_DOMAIN=update-ubuntu-18-dnsimple.xyz
    - TASK="kitchen" KITCHEN_REGEXP=update-record-ubuntu-2004 DNSIMPLE_TEST_DOMAIN=update-ubuntu-20-dnsimple.xyz

matrix:
  fast_finish: true

install: echo "skip bundle install"

before_install:
  - curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chef-workstation

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - chef gem install dnsimple -v '< 6.0'

script:
  - chef exec rake $TASK

after_failure:
  - which chef
  - chef -v
  - chef exec kitchen list
  - chef exec kitchen diagnose $KITCHEN_REGEXP

notifications:
  email: false
  slack:
    secure: S/tClOuaGnhxdCkyc3WT0kWy9fP4a9dI7Ha0Pk0sjC0Fy1+0V/AShxwfgzJdGlzvbsRlCXmkE8W4BEQmZ0HjiPZgrvOx9mxv1krbBaO+eZDiSJIv2NgkgbwcxfraD+V3s4Mo8q3/FtS27diBOOUip4xqETsAIx0X86ZjHcb21ew=
