version: 2.1

executors:
  chefdk:
    machine: true

jobs:
  lint:
    executor: chefdk
    steps:
      - checkout
      - run:
          name: Install ChefDK
          command: curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -c stable -P chefdk
      - run:
          name: Add dnsimple gem
          command: chef gem install dnsimple
      - run:
          name: Lint & Unit Test
          command: chef exec rake quick

workflows:
  lint_and_test:
    jobs:
      - lint
