version: 2.1

executors:
  chef:
    machine: true

jobs:
  lint:
    executor: chefdk
    steps:
      - checkout
      - run:
          name: Install ChefDK
          command: curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -c stable -P chefdk
      - run:
          name: Lint & Unit Test
          command: chef exec rake quick
