version: 2.1

executors:
  chefdk:
    docker:
      - image: chef/chefdk:3

jobs:
  setup:
    executor: chefdk
    steps:
      - checkout
      - run:
          name: Add dnsimple gem
          command: chef gem install dnsimple
  lint:
    executor: chefdk
    steps:
      - run:
          name: Lint & Unit Test
          command: chef exec rake quick

workflows:
  version: 2
  lint_and_test:
    jobs:
      - setup
      - lint:
        requires:
          - setup
