version: 2.1

jobs:
  delivery:
    docker:
      - image: chef/chefdk:3
    steps:
      - checkout
      - run:
          name: Add dnsimple gem
          command: chef gem install dnsimple
      - run: delivery local all
  dokken:
    machine: true
    parameters:
      domain:
        description: Test domain for dnsimple sandbox
        type: string
        default: example.com
      suite:
        description: Test kitchen suite name
        type: string
    environment:
      DNSIMPLE_TEST_DOMAIN: <<parameters.domain>>
      KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
    steps:
      - checkout
      - run:
          name: Install Chef
          command: curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -c stable -P chefdk
      - run:
          name: Add dnsimple gem
          command: chef gem install dnsimple
      - run:
          name: centos-6
          domain: <<parameters.suite>>-6-dnsimple.xyz
          command: kitchen test <<parameters.suite>>-centos-6


workflows:
  test_kitchen:
    jobs:
      - delivery
      - dokken:
          name: create-record
          suite: create-record
